spring.application.name=EclipseProtocol

spring.datasource.url=jdbc:h2:mem:eclipseprotocol
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.github.client-id=Ov23liKnTer3C7Og2Fq4
spring.security.oauth2.client.registration.github.client-secret=607a9f60f658b55659e1463e24966dfcd9ebb49f
spring.security.oauth2.client.registration.github.scope=read:user,user:email
