spring.application.name=EclipseProtocol

# H2 - banco e teste para desenvolvimento
spring.datasource.url=jdbc:h2:mem:eclipseprotocol
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# jpa - muita atenção nesse aquivo, se tiver algo errado aqui, o banco não vai funcionar
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
